version: '3.8'

services:
  mysqldb:
    image: mysql:8
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foyer
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dev-network

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-backend
    ports:
      - "8086:8086"  # Maps container's port 8086 to host
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/foyer?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SERVER_PORT: 8086
      SERVER_SERVLET_CONTEXT_PATH: /Foyer
    networks:
      - dev-network

networks:
  dev-network:

volumes:
  mysql_data:
